
comp: queueTest stackTest

queueTest: playQueue.c Queue.c Point2D.c
	gcc -o queueTest -Wall playQueue.c Queue.c Point2D.c

stackTest: playStack.c Stack.c Point2D.c
	gcc -o stackTest -Wall playStack.c Stack.c Point2D.c
